package com.contagotas.contagotas.data.DAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.contagotas.contagotas.data.DAO.MediaGastos;
import com.contagotas.contagotas.data.DAO.DetalheGastos;

import com.contagotas.contagotas.data.DAO.MediaGastosDao;
import com.contagotas.contagotas.data.DAO.DetalheGastosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mediaGastosDaoConfig;
    private final DaoConfig detalheGastosDaoConfig;

    private final MediaGastosDao mediaGastosDao;
    private final DetalheGastosDao detalheGastosDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mediaGastosDaoConfig = daoConfigMap.get(MediaGastosDao.class).clone();
        mediaGastosDaoConfig.initIdentityScope(type);

        detalheGastosDaoConfig = daoConfigMap.get(DetalheGastosDao.class).clone();
        detalheGastosDaoConfig.initIdentityScope(type);

        mediaGastosDao = new MediaGastosDao(mediaGastosDaoConfig, this);
        detalheGastosDao = new DetalheGastosDao(detalheGastosDaoConfig, this);

        registerDao(MediaGastos.class, mediaGastosDao);
        registerDao(DetalheGastos.class, detalheGastosDao);
    }
    
    public void clear() {
        mediaGastosDaoConfig.getIdentityScope().clear();
        detalheGastosDaoConfig.getIdentityScope().clear();
    }

    public MediaGastosDao getMediaGastosDao() {
        return mediaGastosDao;
    }

    public DetalheGastosDao getDetalheGastosDao() {
        return detalheGastosDao;
    }

}
