package com.contagotas.contagotas.data.DAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDIA_GASTOS.
 */
public class MediaGastos {

    private Long id;
    private Float total;
    private String data;
    private Boolean is_deleted;

    public MediaGastos() {
    }

    public MediaGastos(Long id) {
        this.id = id;
    }

    public MediaGastos(Long id, Float total, String data, Boolean is_deleted) {
        this.id = id;
        this.total = total;
        this.data = data;
        this.is_deleted = is_deleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getTotal() {
        return total;
    }

    public void setTotal(Float total) {
        this.total = total;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

}
