package com.contagotas.data.DAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDIA_GASTOS.
 */
public class MediaGastos {

    private Long id;
    private Integer total;
    private String data;
    private String deleted;

    public MediaGastos() {
    }

    public MediaGastos(Long id) {
        this.id = id;
    }

    public MediaGastos(Long id, Integer total, String data, String deleted) {
        this.id = id;
        this.total = total;
        this.data = data;
        this.deleted = deleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

}
